### ISSUE TITLE
Wrong Format OffsetDateTime

### ISSUE THREAD

**Issue by karun2189** [JakeWharton/ThreeTenABP#129] opened 2020-10-17 05:34 UTC
Hi,

OffsetDateTime.now() is changing.

LogUtils.e("Converter","Before Current Offset : ${OffsetDateTime.now()}")
val oTs = OffsetDateTime.now()?.format(DateTimeFormatter.ISO_ZONED_DATE_TIME)
LogUtils.e("Converter","Offset to String : $oTs")
LogUtils.e("Converter","After Current Offset : ${OffsetDateTime.now()}")

Before Current Offset : 2020-10-17T10:55:33.559+05:30
Offset to String : 2020-10-17T05:25:33.561Z
After Current Offset : 2020-10-17T05:25:33.564Z

Any help?

I am using timber and threetenabp also

**com.jakewharton.timber:timber:4.7.1**

**com.jakewharton.threetenabp:threetenabp:1.2.4**

**Comment by JakeWharton** [comment] 2020-10-17 15:46
Dupe of https://github.com/ThreeTen/threetenbp/issues/138. Please don't cross post issues and split discussion.

**Closed by JakeWharton** 2020-10-17 15:46 UTC
