### ISSUE TITLE
incorrect result of dayOfWeek.getDisplayName(TextStyle.NARROW, Locale.getDefault())

### ISSUE THREAD

**Issue by VinsonGuo** [JakeWharton/ThreeTenABP#90] opened 2018-11-14 05:24 UTC
Thanks your library help to develop, but I find an exception when I used "LocalDate.now().dayOfWeek.getDisplayName(TextStyle.NARROW or STANDALONG, Locale.getDefault())". My Location and device region is China, System language is Chinese. For example, today is Wednesday, the correct result should be “三” (third) instead of "星" and other day's result is "星" which should be "一、二、三...". When I set locale to US, the result is "W", it's right.

**Comment by JakeWharton** [comment] 2018-11-14 06:01
Dupe of https://github.com/ThreeTen/threetenbp/issues/97

**Closed by JakeWharton** 2018-11-14 06:01 UTC
